version: '3'

services:
  dog-server:
    image: scaddie-image
    container_name: 'a-container'
    volumes:
      - ./a-container/app:/app
    ports:
      - 7000:80

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80